### ISSUE TITLE
Crashing on CTRL+C

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#260] opened 2022-07-03 22:50 UTC
**Describe the bug**
Sometimes, when closing the app using `ctrl+c` the app crash

**To Reproduce**
1. Run the app
2. press CTRL+C
3. Repeat step 1 until the crash

**Expected behavior**
A clean close of the app without panic

**Screenshots**
App crashing
![image (4)](https://user-images.githubusercontent.com/35319980/177059783-2cf0d7af-01c8-4576-9162-fbdd71589ca5.png)

**Comment by D-DePablos** [comment] 2022-07-22 15:29
I can't reproduce this on main, is this fixed now @stdevMac ?

**Comment by tshakalekholoane** [comment] 2022-07-26 14:02
Fixed by #288.

**Closed by tshakalekholoane** 2022-07-26 14:02 UTC
Labels: bug
