### ISSUE TITLE
Health Check for Node

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#229] opened 2022-06-19 19:17 UTC
We should be able to provide a RPC endpoint, and API endpoint that basically knows when the node is running properly, the db connections are ok, and the feeder gateway is responding well.

**Comment by v4lproik** [comment] 2022-07-04 17:08
Anyone tackling this issue? I don't mind giving it a try it as I need an health check for the k8s deployment.

**Comment by v4lproik** [comment] 2022-07-05 09:35
After looking into this, several questions came to mind including:
- Mdbx database doesn't have a sort of a 'PING' request meaning that either we base our check using the [open](https://github.com/torquem-ch/mdbx-go/blob/e31bb2988dcec049cff3084b08f2071530c32636/mdbx/env.go#L150) function or using a function calling the database (eg. get(key)). Any thoughts?
- After reading the alpha mainnet documentation, it doesn't seem there's an endpoint exposing the gateway feeder status. Same comment as before, should we base the check on a get(transactionId) sort of request?

**Comment by stdevMac** [comment] 2022-07-05 10:32
We are doing some arrangements around how we set the services to each of them will contain a health check, will be better to wait until that is done, thanks for pointing out this! We assume the database is ok because if there is any corruption appears at any time, the app is going to close, basically because is the core and if you have any problem, you will not be able of retrieve/store any info needed and the node will close

**Comment by v4lproik** [comment] 2022-07-05 10:39
Yes, it definetly sounds like a good idea to add an healthcheck for each service. More resilient and easier to pin point exactly which service is not available when downtime occurs.
Oh I see, thanks for the explanation about the database!

**Comment by stdevMac** [comment] 2022-07-05 10:47
Thanks for your contributions! if any other question appears, let us know! Looking forward for more adds from your side

**Comment by tshakalekholoane** [comment] 2022-08-11 11:56
Possible duplicate of #324.

**Closed** 2022-09-01 14:34 UTC
Labels: enhancement, db, core, rpc
