### ISSUE TITLE
Logging is not working on feeder client

### ISSUE THREAD

**Issue by Brivan-26** [NethermindEth/juno#1166] opened 2023-08-24 16:56 UTC
[This logging](https://github.com/NethermindEth/juno/blob/121122badf30b987a3abd674d7f21581db7c0ef7/clients/feeder/feeder.go#L237) is not working properly.

### How to reproduce the issue
Give an invalid request to the feeder gateway, the following line will not print to console:
```go
c.log.Warnw("failed query to feeder, retrying...", "retryAfter", wait.String())
```

**Comment by joshklop** [comment] 2023-08-24 17:00
See comment [here](https://github.com/NethermindEth/juno/pull/1085#discussion_r1300639475).

**Comment by joshklop** [comment] 2023-08-24 17:01
I think this is a duplicate of #1020. If you agree, do you mind closing @Brivan-26?

**Comment by Brivan-26** [comment] 2023-08-24 17:02
> I think this is a duplicate of #1020. If you agree, do you mind closing @Brivan-26?

I didn't notice that issue.
Yes please, go ahead.

**Closed** 2023-08-24 17:02 UTC
